name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set node
        uses: actions/setup-node@v3
        with:
          registry-url: https://registry.npmjs.org/
          node-version: 16.x

      - name: Setup
        run: npm i -g @antfu/ni

      - name: Install
        run: nci

      - name: Build
        run: nr build:deploy

      - name: Ssh-deploy
        uses: easingthemes/ssh-deploy@v2
        env:
          ARGS: "-avz --delete"
          SSH_PRIVATE_KEY: ${{ secrets.ECS_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.ECS_SERVER_HOST }}
          REMOTE_USER: ${{ secrets.ECS_REMOTE_USER }}
          SOURCE: "docs/.vuepress/dist"
          TARGET: "/root/notes"
